version: "3.8"

services:
  elasticsearch:
    image: "elasticsearch:7.6.0"
    container_name: "lab7-minidatadogdock-elasticsearch"
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: "kibana:7.6.0"
    container_name: "lab7-minidatadog-kibana"
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_CONTAINER=true

  logstash:
    image: logstash:7.6.0
    container_name: "lab7-minidatadog-logstash"
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      - ES_URL=http://elasticsearch:9200